name: magic_ext_oauth
description: A Magic oauth extension to support Magic social login authentication
version: 0.3.5
homepage: https://magic.link
repository: https://github.com/magiclabs/magic-flutter


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  magic_sdk: ^5.1.0
  # magic_sdk:
  #  path: "../../magic_sdk"
  package_info_plus: ^4.2.0
  uri: ^1.0.0
  flutter_web_auth: ^0.5.0
  crypto: ^3.0.1
  json_annotation: ^4.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
