name: magic_ext_oidc
description: A Magic extension to enable signing with OpenId on Flutter. Magic SDK is your entry-point to integrating passwordless authentication inside your application.
version: 0.0.1
homepage: https://magic.link
repository: https://github.com/magiclabs/magic-flutter

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  magic_sdk:
    #    path: ../mattel-magic-sdk/magic-flutter/packages/magic_sdk/
    git:
      url: git@github.com:Mattel/magic-flutter.git
      ref: dev
      path: packages/magic_sdk
  web3dart: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
